spring:
  application:
    name: 'astronaut-api'
    
server:
  port: 8080
  servlet:
    context-path: '/api'

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
